server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sandbox
    username: postgres
    password: samar
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      initialization-fail-timeout: 0

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
        generate_statistics: true

  sql:
    init:
      mode: never
      schema-locations: ''
      data-locations: ''

  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 100
        thread-name-prefix: app-thread-

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Sandbox

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE
    org.springframework:
      web: DEBUG
    com:
      example:
        sandboxspring: INFO
